### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by julesvirallinen** [Attacks-on-Tor/Attacks-on-Tor#1]
If possible, could you release the bibliography to the end of the .md file, to make the markdown version readable with the citations.

**Comment by HansSchouten** [comment]
Thanks for your suggestion. I added the references and made the citations clickable.

**Comment by julesvirallinen** [comment]
Thanks. Can I ask what context this was made in? A seminar? Why did you not publish it somewhere?

**Comment by HansSchouten** [comment]
Yep, it was written as part of a Bachelor seminar with @synctext at Delft University of Technology. It was just one busy quarter and did not think about anything other than quickly publishing it on GitHub.

**Comment by julesvirallinen** [comment]
Nice, I'm doing my own on a subtopic of this so it's very useful nevertheless. Your categorization and taxonomy of the different attacks is the best I've seen, I haven't seen any academic papers that attempt to categorize most attacks

**Comment by synctext** [comment]
@julkku would you like to contribute your work to this repo and extend it?
Great if this would continue.

**Comment by julesvirallinen** [comment]
Interesting offer! My priority right now is finishing my own paper, but I'll think about it!
